-- Plugins
require('plugins.lazy')
require('plugins.nvim-cmp')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.zen')
require('plugins.lua-snippets')
require('plugins.lualine-conf')
require('plugins.tree')
require('plugins.nightfox')
require('plugins.mason')
require('plugins.rust-tools')
